### ISSUE TITLE
Not an issue.. just a question.. wondering if this still worked or if anyone was working on it.

### ISSUE THREAD

**Issue by jacksnodgrass** [angrychimp/php-myq-liftmaster#1]
Got an Amazon Dot ( Alexa thingie ) for Christmas.. have it hooked up to my X10 lights and onkyo stereo... my MyQ garage doors are next on the integration list. Just curious to know if this project still worked or was being worked on. - jack

**Comment by angrychimp** [comment]
Heh, to be honest I had completely forgotten about this. I ended up cheating and getting a Wink and connecting it to that. But I can certainly jump back on this and see if I can get it back up to snuff. Were you looking to develop a custom Skill for the door?

**Comment by nelis249** [comment]
It actually does work. Well it did. As of Fri 3, 2017, the myqdevice.com web site must have changed the API as attempts to logon result in "Your request has been denied." Either they had an update or just removed the API altogether, I'm not certain. I've been trying to reverse engineer the Myq app on my android to figure out what the API might be calling now bu haven't had any luck yet.

You can see for yourself just by browsing to:
https://myqexternal.myqdevice.com/Membership/ValidateUserWithCulture?appId=Vj8pQggXLhLy0WHahglCD4N1nAkkXQtGYpq2HrHD7H1nvmbT55KqtN6RSF4ILB%2fi&username=yourid&password=yourpass&culture=en

Prior to last friday that was returning a json object that had all the info.

Thought if Wink is talking to garage doors then there has to be some capability that's just not published.

**Comment by angrychimp** [comment]
Ok, tonight I'll load up Fiddler again and see if I can capture the app traffic again. Thanks for the update.

**Comment by nelis249** [comment]
howdy,

Didn't think this was still alive. After investigating it seems as the logonURL that I had was updated to the one in this Github publishing. I'm not quite sure where the heck I got the URL from.

I do have to use appId
protected $_appId = 'Vj8pQggXLhLy0WHahglCD4N1nAkkXQtGYpq2HrHD7H1nvmbT55KqtN6RSF4ILB%2fi';
Which is in the comments.

Anyways, this code works. No need to fiddler it.
