### ISSUE TITLE
README.md setup instructions. 

### ISSUE THREAD

**Issue by jacksnodgrass** [angrychimp/php-myq-liftmaster#3]
After cloning the repo, edit the `sample.config.ini` file to add your username/email and password. 

Should say something about copying the sample.config.ini  file to config.ini and changing the values in there. Yes.. obvious to most tinkerers... but still useful for people looking at this before their first cup of coffee kicks in. 

- jack

**Comment by angrychimp** [comment]
Fixed with commit 1483add
