### ISSUE TITLE
MYQ_DOOR_STATE_UNKNOWN  is misspelled on line: 34 in MyQ.php

### ISSUE THREAD

**Issue by jacksnodgrass** [angrychimp/php-myq-liftmaster#4]
protected $_stateDescriptions = array (
        MYQ_DOOR_STATE_UNKNOWN => 'unknown', <--- should be: MYQ_DOOR_STATE_UKNOWN
        MYQ_DOOR_STATE_OPEN => 'open',
        MYQ_DOOR_STATE_CLOSED => 'closed',
        MYQ_DOOR_STATE_OPENING => 'opening',
        MYQ_DOOR_STATE_CLOSING => 'closing',
    );

door.php gives and error: 

PHP Notice:  Use of undefined constant MYQ_DOOR_STATE_UNKNOWN - assumed 'MYQ_DOOR_STATE_UNKNOWN' in /home/jack/IoT/php-myq-liftmaster/MyQ.php on line 405

**Comment by angrychimp** [comment]
Corrected the constant names. Thanks.
